version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - ECR_URI=$<ECR 링크>
      - IMAGE_TAG=$(TZ=Asia/Seoul date +"%y-%m-%d.%H.%M.%S")
      - <ECR 푸시 명령 인증>
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_URI:latest .
      - docker tag $ECR_URI:latest $ECR_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo Writing image definition file...
      - echo "$(jq .containerDefinitions[0].image=\"$ECR_URI:$IMAGE_TAG\" taskdef.json)" > taskdef.json
artifacts:
  files:
    - 'appspec.yml'
    - 'taskdef.json'
