kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: <RBAC 역활 이름>
  namespace: <네임스페이스>
rules:
  - apiGroups: 
    - '*'
    resources:
    - '*'
    verbs: 
    - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin-rolebinding
  namespace: <네임스페이스>
subjects:
- kind: User
  name: <Aws Auth UserName>
roleRef:
  kind: Role
  name: <RBAC 역활 이름>
  apiGroup: rbac.authorization.k8s.io
