apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: infra-cluster
  region: ap-northeast-2
  version: "1.28"

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: autoscaler-service
      namespace: kube-system
    attachPolicy:
      Version: "2012-10-17"
      Statement:
      - Effect: Allow
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeAutoScalingInstances"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:DescribeTags"
        - "autoscaling:SetDesiredCapacity"
        - "autoscaling:TerminateInstanceInAutoScalingGroup"
        - "ec2:DescribeLaunchTemplateVersions"
        Resource: '*'

vpc:
  subnets:
    public:
      ap-northeast-2a: { id: public_a }
      ap-northeast-2b: { id: public_b }
      ap-northeast-2c: { id: public_c }
    private:
      ap-northeast-2a: { id: private_a }
      ap-northeast-2b: { id: private_b }
      ap-northeast-2c: { id: private_c }

managedNodeGroups:
  - name: skills-app
    instanceName: skoills-app
    labels: { skills/dedicated: app }
    tags: { skills/dedicated: app }
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
  - name: skills-addon
    instanceName: skoills-addon
    labels: { skills/dedicated: addon }
    tags: { skills/dedicated: addon }
    instanceType: c5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
