apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: <클러스터 이름>
  region: <리전>
  version: "<쿠버네티스 버전>"
  
cloudWatch:
  clusterLogging:
    enableTypes:
    - "api"
    - "audit"
    - "authenticator"
    - "controllerManager"
    - "scheduler"
    
iam:
  withOIDC: true
vpc:
  id: <vpc 아이디>
  subnets:
    public:
      <리전>a-pub: { id: (서브넷 아이디) }
      <리전>b-pub: { id: (서브넷 아이디) }
    private:
      <리전>a-priv: { id: (서브넷 아이디) }
      <리전>b-priv: { id: (서브넷 아이디) }
